#!/usr/bin/env -S uv run

# /// script
# dependencies = [
#   "tqdm",
# ]
# ///

r"""
Process unprocessed bookmarks from a CSV file: download and summarize each
Hacker News submission, save a merged summary to a destination, and mark
the row as done.

For each row without the `Done` flag set (up to `--limit` rows), this:

1) Downloads and summarizes the submission via `download_hn_article_to_md.py`
   (article + HN comments, saved under `--output_dir`)
2) Merges the article summary and HN comments summary into a single
   `<date>.hn_<item_id>.<title>.summary.md` file, prefixed with a backlink
   header (`Article: <url>` / `HN: <url>`)
3) Saves a `<date>.hn_<item_id>.<title>.stats.json` file under
   `--output_dir` with the wallclock time spent downloading and the LLM
   usage stats (model, char counts, wallclock time, cost) for both
   summarization phases
4) Sets `Done=yes` for that row and saves the CSV in place

A row whose `Hn_url` isn't a real HN item URL (`news.ycombinator.com/
item?id=...`) is set to `Done=skipped` immediately instead, with no
download.

Separately, every invocation also runs a **destination reconciliation
pass** over *all* `Done=yes` rows (not bounded by `--limit`): for the
`--dest_type`/`--dest_dir` selected this run, any row whose cached merged
summary (under `--output_dir`) is missing from the destination gets copied
there -- no re-download, no re-summarize, no LLM cost. This is what makes
`--dest_type gdrive` and `--dest_type obsidian` independent: switching to a
new destination later backfills it for free from rows already processed.
`--limit 0` runs reconciliation only (no new rows processed).

The cost of each row's 2 summarization phases (article + HN comments) is
summed into a running total, shown in the progress bar and logged at the
end as the total summarization cost for the run.

# Usage Example

- Process up to 10 unprocessed rows (default), copying to Google Drive:
> process_bookmarks.py \
    --input /Users/saggese/src/notes1/bookmarks/update_gsheet_links_from_raindrop.combined_data.csv \
    --limit 10

- Preview what would be done without downloading/writing anything:
> process_bookmarks.py --input bookmarks.csv --dry_run

- Reprocess rows even if already marked `Done`, overwriting existing local
  output files:
> process_bookmarks.py --input bookmarks.csv --no_incremental

- Copy merged summaries to the Obsidian vault instead of Google Drive:
> process_bookmarks.py --input bookmarks.csv --dest_type obsidian

- Keep the merged summaries local (under `--output_dir`) only:
> process_bookmarks.py --input bookmarks.csv -o ./tmp.hn_downloads \
    --dest_type none

- Backfill a destination for rows already processed, without downloading
  anything new:
> process_bookmarks.py --input bookmarks.csv --dest_type obsidian --limit 0

Import as:

import dev_scripts_helpers.download.process_bookmarks as dshdprbo
"""

import argparse
import dataclasses
import glob
import logging
import os
import shutil
import time
from typing import Any, Dict, List, Optional, Tuple

from tqdm import tqdm

import helpers.hdbg as hdbg
import helpers.hgit as hgit
import helpers.hio as hio
import helpers.hllm_cli as hllmcli
import helpers.hparser as hparser
import helpers.hprint as hprint
import helpers.hsystem as hsystem
import dev_scripts_helpers.download.bookmark_utils as dshdbout

_LOG = logging.getLogger(__name__)

# Default local dir for the raw per-item files (article/comments + their
# summaries) generated by `download_hn_article_to_md.py`.
_DEFAULT_OUTPUT_DIR = "./tmp.process_bookmarks.hn_downloads"
# Default dirs the merged per-item summaries are copied to, one per
# `--dest_type` (`none` has no default dir: nothing is copied).
_DEFAULT_GDRIVE_DIR = (
    "/Users/saggese/Library/CloudStorage/GoogleDrive-saggese@gmail.com/"
    "My Drive/HN"
)
_DEFAULT_OBSIDIAN_DIR = (
    "/Users/saggese/Library/Mobile Documents/iCloud~md~obsidian/"
    "Documents/GP/"
)
_DEFAULT_LIMIT = 10

# Suffixes of the 2 summary files generated by `download_hn_article_to_md.py`
# that get merged together (see its docstring for the full filename
# convention).
_ARTICLE_SUMMARY_SUFFIX = ".2.article_url.summary.md"
_HN_SUMMARY_SUFFIX = ".4.hn_url.summary.md"


# #############################################################################
# Backlink header parsing / merged summary
# #############################################################################


def _parse_backlink_header(content: str) -> Tuple[str, str, str]:
    """
    Split a `Article: <url>` / `HN: <url>` backlink header off the front of
    `content` (added by `download_hn_article_to_md.py`).

    :param content: file content, optionally starting with the backlink
        header lines
    :return: (article_url, hn_url, remaining content); `article_url` is
        `""` if the header has no `Article:` line
    """
    _LOG.debug(hprint.to_str("content"))
    lines = content.split("\n")
    article_url = ""
    hn_url = ""
    idx = 0
    while idx < len(lines):
        if lines[idx].startswith("Article: "):
            article_url = lines[idx][len("Article: ") :]
            idx += 1
        elif lines[idx].startswith("HN: "):
            hn_url = lines[idx][len("HN: ") :]
            idx += 1
        else:
            break
    # Skip the blank line separating the header from the content.
    if idx < len(lines) and lines[idx] == "":
        idx += 1
    rest = "\n".join(lines[idx:])
    _LOG.debug(hprint.to_str("article_url hn_url"))
    return article_url, hn_url, rest


def _strip_leading_h1(text: str) -> str:
    """
    Drop a leading top-level (`# ...`) heading line from `text`, if present.

    Used to avoid duplicating the LLM's own top-level heading (e.g., `#
    Article Summary`, `# HN Comments Summary`) underneath the hardcoded
    section heading `_build_merged_summary` already adds.

    :param text: section content, optionally starting with a `# ...` heading
    :return: `text` with the leading `# ...` heading (and the blank line
        after it) removed, if present
    """
    lines = text.split("\n")
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        if lines and lines[0] == "":
            lines = lines[1:]
    return "\n".join(lines)


def _build_info_section(
    row: Dict[str, Any], article_url: str, hn_url: str
) -> str:
    """
    Build the `# Info` section listing the row's metadata.

    :param row: CSV row dict (`Title`, `Timestamp`, `Article_tag`,
        `Article_cluster` are read from it, if present)
    :param article_url: article URL, empty for Show HN / Ask HN / text posts
    :param hn_url: HN submission URL
    :return: `# Info` section text (no trailing blank line)
    """
    lines = ["# Info"]
    title = (row.get("Title") or "").strip()
    if title:
        lines.append(f"Title: {title}")
    if article_url:
        lines.append(f"Article: {article_url}")
    lines.append(f"HN: {hn_url}")
    for key, label in (
        ("Timestamp", "Timestamp"),
        ("Article_tag", "Article_tag"),
        ("Article_cluster", "Article_cluster"),
    ):
        value = (row.get(key) or "").strip()
        if value:
            lines.append(f"{label}: {value}")
    return "\n".join(lines)


def _build_merged_summary(
    row: Dict[str, Any],
    hn_summary_file: str,
    article_summary_file: Optional[str],
) -> Tuple[str, str]:
    """
    Merge the article summary and HN comments summary into a single file.

    :param row: CSV row dict, used to populate the `# Info` section
    :param hn_summary_file: path to the `*.4.hn_url.summary.md` file
        (always present)
    :param article_summary_file: path to the `*.2.article_url.summary.md`
        file, or None if the submission has no linked article
    :return: (merged file name, merged file content)
    """
    _LOG.debug(hprint.to_str("hn_summary_file article_summary_file"))
    hn_filename = os.path.basename(hn_summary_file)
    hdbg.dassert(
        hn_filename.endswith(_HN_SUMMARY_SUFFIX),
        "Unexpected HN summary filename: %s",
        hn_filename,
    )
    base_name = hn_filename[: -len(_HN_SUMMARY_SUFFIX)]
    article_url, hn_url, hn_rest = _parse_backlink_header(
        hio.from_file(hn_summary_file)
    )
    if article_summary_file:
        article_url2, _, article_rest = _parse_backlink_header(
            hio.from_file(article_summary_file)
        )
        # Prefer the article URL from the article summary's own header, if
        # present; fall back to the one parsed from the HN summary.
        article_url = article_url2 or article_url
    else:
        article_rest = "No linked article (Show HN / Ask HN / text post)."
    info_section = _build_info_section(row, article_url, hn_url)
    sections = [
        "# Article Summary\n\n" + _strip_leading_h1(article_rest.strip()),
        "# HN Comments Summary\n\n" + _strip_leading_h1(hn_rest.strip()),
    ]
    merged_content = info_section + "\n\n" + "\n\n".join(sections) + "\n"
    merged_filename = f"{base_name}.summary.md"
    _LOG.debug(hprint.to_str("merged_filename"))
    return merged_filename, merged_content


# #############################################################################
# Stats
# #############################################################################


def _get_stat_file_path(summary_file: str) -> str:
    """
    Derive the stats JSON file path for a summary file.

    Duplicates `download_utils.get_stat_file_path()` rather than importing
    it: `download_utils.py` pulls in `bs4`/`requests`, which aren't in this
    script's `uv run` inline dependency list (kept minimal since this script
    only shells out to `download_hn_article_to_md.py` instead of fetching
    content itself).

    :param summary_file: path to a `*.summary.md` file produced by
        `download_utils.summarize_text_with_llm()`
    :return: path to the sibling stats file (e.g.,
        `foo.summary.md` -> `foo.summary.stat.json`)
    """
    hdbg.dassert(
        summary_file.endswith(".md"),
        "Summary file must end in '.md': %s",
        summary_file,
    )
    return summary_file[: -len(".md")] + ".stat.json"


def _load_stats(stat_file: str) -> Optional[Dict[str, Any]]:
    """
    Load a `TokenStats` JSON file saved by `llm_cli.py --stat_file`.

    :param stat_file: path to the stats JSON file
    :return: stats as a dict, or None if the file doesn't exist (e.g., the
        summarization was skipped because the summary already existed)
    """
    if not os.path.exists(stat_file):
        _LOG.warning("Stats file not found, skipping: '%s'", stat_file)
        return None
    token_stats = hllmcli.TokenStats.from_file(stat_file)
    return dataclasses.asdict(token_stats)


def _get_cost(stats: Optional[Dict[str, Any]]) -> float:
    """
    Extract the cost in dollars from a `TokenStats`-shaped dict.

    Prefers `cost_from_tokencost`, falling back to `cost_from_llm_library`
    (mirrors `hllmcli.TokenStats.to_float()`).

    :param stats: `TokenStats` dict (e.g., `article_summary_stats` or
        `hn_summary_stats`), or None if that summarization phase was skipped
    :return: cost in dollars, or 0.0 if `stats` is None
    """
    if not stats:
        return 0.0
    cost_from_tokencost = stats.get("cost_from_tokencost") or 0.0
    cost_from_llm_library = stats.get("cost_from_llm_library") or 0.0
    if cost_from_tokencost > 0:
        return float(cost_from_tokencost)
    return float(cost_from_llm_library)


def _build_stats(
    merged_filename: str,
    total_wallclock_time_in_seconds: float,
    hn_summary_file: str,
    article_summary_file: Optional[str],
) -> Tuple[str, Dict[str, Any], float]:
    """
    Build the per-row stats file name and content.

    :param merged_filename: name of the merged summary file (as returned by
        `_build_merged_summary()`), used to derive the stats file name
    :param total_wallclock_time_in_seconds: wallclock time of the whole
        `download_hn_article_to_md.py` invocation (download + summarize)
    :param hn_summary_file: path to the `*.4.hn_url.summary.md` file
    :param article_summary_file: path to the `*.2.article_url.summary.md`
        file, or None if the submission has no linked article
    :return: (stats file name, stats dict, total cost in dollars of the 2
        summarization phases)
    """
    hn_stats = _load_stats(_get_stat_file_path(hn_summary_file))
    article_stats = (
        _load_stats(_get_stat_file_path(article_summary_file))
        if article_summary_file
        else None
    )
    # The download wallclock time is the total time minus the time spent in
    # the 2 LLM summarization calls (already reported individually in
    # `hn_stats` / `article_stats`).
    summarize_time = sum(
        stats["elapsed_time_in_seconds"]
        for stats in (hn_stats, article_stats)
        if stats
    )
    download_wallclock_time_in_seconds = max(
        0.0, total_wallclock_time_in_seconds - summarize_time
    )
    # Sum the cost of both summarization phases (article + HN comments).
    total_cost_in_dollars = _get_cost(article_stats) + _get_cost(hn_stats)
    stats = {
        "total_wallclock_time_in_seconds": total_wallclock_time_in_seconds,
        "download_wallclock_time_in_seconds": (
            download_wallclock_time_in_seconds
        ),
        "total_cost_in_dollars": total_cost_in_dollars,
        "article_summary_stats": article_stats,
        "hn_summary_stats": hn_stats,
    }
    hdbg.dassert(
        merged_filename.endswith(".summary.md"),
        "Unexpected merged filename: %s",
        merged_filename,
    )
    stats_filename = merged_filename[: -len(".summary.md")] + ".stats.json"
    return stats_filename, stats, total_cost_in_dollars


# #############################################################################
# Row selection
# #############################################################################


def _select_rows(
    rows: List[Dict[str, Any]], *, no_incremental: bool, limit: int
) -> List[Dict[str, Any]]:
    """
    Select up to `limit` rows to process, logging the incremental counts.

    :param rows: all CSV rows
    :param no_incremental: if True, select from all rows (even ones already
        marked `Done`) instead of only the unprocessed ones
    :param limit: max number of rows to select
    :return: rows to process this run (references into `rows`, so mutating
        them mutates `rows` too)
    """
    _LOG.debug(hprint.to_str("no_incremental limit"))
    done_rows = [r for r in rows if (r.get("Done") or "").strip()]
    not_done_rows = [r for r in rows if not (r.get("Done") or "").strip()]
    _LOG.info("Rows already processed (Done set): %d", len(done_rows))
    _LOG.info("Rows needing processing: %d", len(not_done_rows))
    candidates = rows if no_incremental else not_done_rows
    selected = candidates[:limit]
    _LOG.info(
        "Selected %d row(s) to process this run (limit=%d)",
        len(selected),
        limit,
    )
    return selected


# #############################################################################
# Destination resolution
# #############################################################################


def _resolve_dest_dir(dest_type: str, dest_dir: str) -> Optional[str]:
    """
    Resolve the destination dir for the selected `--dest_type`.

    :param dest_type: `"gdrive"`, `"obsidian"`, or `"none"`
    :param dest_dir: `--dest_dir` override, or `""` to use the built-in
        default path for `dest_type`
    :return: absolute path to the destination dir, or `None` for
        `dest_type="none"` (nothing to copy to)
    """
    _LOG.debug(hprint.to_str("dest_type dest_dir"))
    if dest_type == "none":
        return None
    if dest_dir:
        return dest_dir
    default_dir_by_type = {
        "gdrive": _DEFAULT_GDRIVE_DIR,
        "obsidian": _DEFAULT_OBSIDIAN_DIR,
    }
    hdbg.dassert_in(dest_type, default_dir_by_type, "Invalid --dest_type")
    return default_dir_by_type[dest_type]


# #############################################################################
# Per-row processing
# #############################################################################


def _process_row(
    row: Dict[str, Any],
    *,
    script: str,
    output_dir: str,
    model: str,
    no_incremental: bool,
    dry_run: bool,
) -> Tuple[str, Optional[Dict[str, Any]]]:
    """
    Download, summarize, and save the merged summary for a single row.

    Destination-agnostic: only writes the merged summary and stats under
    `output_dir` and sets `Done`; copying to a destination is handled
    separately by `_reconcile_destination()`, so the same cached file can
    later be backfilled into a different destination without re-processing.

    :param row: CSV row dict; mutated in place (`Done` is set to `"yes"` on
        success, or to `"skipped"` for a row that can never be processed)
    :param script: path to `download_hn_article_to_md.py`
    :param output_dir: local dir for the raw per-item files and the merged
        summary
    :param model: LLM model passed through to `download_hn_article_to_md.py`
        for both summarization phases; `""` uses that script's own default
    :param no_incremental: if True, force `download_hn_article_to_md.py` to
        overwrite existing local per-item files
    :param dry_run: if True, log what would be done without doing it
    :return: a tuple
        - status: `"processed"` (`Done` set to `"yes"`), `"skipped"` (`Done`
          set to `"skipped"`; `Hn_url` isn't a real HN item URL, so the row
          can never be processed by this script), `"dry_run"` (`--dry_run`,
          row otherwise valid), or `"failed"` (download/summarize error;
          `Done` left unset so the row is retried next run)
        - the full contents of the saved `*.stats.json` file (read back from
          disk), or None unless status is `"processed"`
    """
    _LOG.debug(
        hprint.to_str("output_dir model no_incremental dry_run")
    )
    hn_url = (row.get("Hn_url") or "").strip()
    if not hn_url or not dshdbout.is_hackernews_url(hn_url):
        _LOG.warning(
            "Skipping row with invalid Hn_url (not a Hacker News item "
            "URL): '%s'",
            hn_url,
        )
        if not dry_run:
            # Permanently skip: this row can never be processed by this
            # script (e.g., a plain article link Raindrop.io put in the
            # Hn_url column), so stop it from occupying --limit slots on
            # every future run. Handling plain-article bookmarks is
            # explicitly out of scope.
            row["Done"] = "skipped"
        return "skipped", None
    item_id = dshdbout.extract_item_id(hn_url)
    title = (row.get("Title") or "").strip()
    if dry_run:
        _LOG.info(
            "[DRY_RUN] Processing item %s: '%s', '%s'",
            item_id,
            hn_url,
            title,
        )
        _LOG.debug(
            "[DRY RUN] Would download+summarize '%s' into '%s' and set "
            "Done=yes",
            hn_url,
            output_dir,
        )
        return "dry_run", None
    _LOG.info(
        "Processing item %s: '%s', '%s'",
        item_id,
        hn_url,
        title,
    )
    # Download and summarize the submission (article + HN comments).
    cmd_parts = [
        script,
        f'--input "{hn_url}"',
        f'--output_dir "{output_dir}"',
    ]
    if model:
        cmd_parts.append(f'--model "{model}"')
    if no_incremental:
        cmd_parts.append("--no_incremental")
    cmd = " ".join(cmd_parts)
    download_start_time = time.time()
    hsystem.system(cmd, print_command=True)
    total_wallclock_time_in_seconds = time.time() - download_start_time
    # Locate the generated summary files: `download_hn_article_to_md.py` owns
    # the exact `<date>.hn_<item_id>.<title>` naming, so glob for it by
    # `item_id` instead of re-deriving the title slug/date here.
    hn_matches = sorted(
        glob.glob(
            os.path.join(output_dir, f"*.hn_{item_id}.*{_HN_SUMMARY_SUFFIX}")
        )
    )
    if not hn_matches:
        _LOG.warning(
            "No HN comments summary generated for item %s, skipping", item_id
        )
        return "failed", None
    hn_summary_file = hn_matches[-1]
    article_matches = sorted(
        glob.glob(
            os.path.join(
                output_dir, f"*.hn_{item_id}.*{_ARTICLE_SUMMARY_SUFFIX}"
            )
        )
    )
    article_summary_file = article_matches[-1] if article_matches else None
    merged_filename, merged_content = _build_merged_summary(
        row, hn_summary_file, article_summary_file
    )
    local_merged_file = os.path.join(output_dir, merged_filename)
    hio.to_file(local_merged_file, merged_content)
    # Save the per-row stats (download wallclock time + both summarization
    # phases' LLM stats) locally, next to the merged summary.
    stats_filename, stats, row_cost_in_dollars = _build_stats(
        merged_filename,
        total_wallclock_time_in_seconds,
        hn_summary_file,
        article_summary_file,
    )
    local_stats_file = os.path.join(output_dir, stats_filename)
    hio.to_json(local_stats_file, stats)
    # Read back the stats file (instead of reusing the in-memory `stats`
    # dict) so the caller gets exactly what was persisted to disk, and
    # decides what to do with it (e.g., extract the cost, log fields).
    row_stats = hio.from_json(local_stats_file)
    _LOG.info(
        "Saved stats to '%s' (cost: $%.6f)",
        local_stats_file,
        row_cost_in_dollars,
    )
    _LOG.info(
        "Saved merged summary to '%s' (destination copy handled by "
        "reconciliation)",
        local_merged_file,
    )
    row["Done"] = "yes"
    return "processed", row_stats


# #############################################################################
# Destination reconciliation
# #############################################################################


def _find_cached_merged_summary(
    output_dir: str, item_id: str
) -> Optional[str]:
    """
    Find the cached `<base>.summary.md` merged-summary file for `item_id`
    under `output_dir`, if `_process_row()` already produced it.

    Globbing for `*.summary.md` also matches the 2 raw per-item summary
    files (`*.2.article_url.summary.md` / `*.4.hn_url.summary.md`), since
    both suffixes end in `.summary.md` too; those are excluded since they
    are merge inputs, not the merge output.

    :param output_dir: local dir holding cached per-item and merged files
    :param item_id: HN item ID (as extracted from `Hn_url`)
    :return: path to the merged summary file, or None if not cached
    """
    candidates = sorted(
        glob.glob(os.path.join(output_dir, f"*.hn_{item_id}.*.summary.md"))
    )
    merged_candidates = [
        c
        for c in candidates
        if not c.endswith(_ARTICLE_SUMMARY_SUFFIX)
        and not c.endswith(_HN_SUMMARY_SUFFIX)
    ]
    if not merged_candidates:
        return None
    return merged_candidates[-1]


def _reconcile_destination(
    rows: List[Dict[str, Any]],
    *,
    output_dir: str,
    dest_dir: Optional[str],
    dry_run: bool,
) -> List[str]:
    """
    Copy the cached merged summary for every `Done=yes` row whose file is
    missing from `dest_dir`.

    Runs over *all* `Done=yes` rows, not bounded by `--limit`: this is what
    makes destinations independent -- running once with one `--dest_type`
    and later with another backfills the new one for free from rows
    already processed, with no re-download, no re-summarize, no LLM cost.

    :param rows: all CSV rows
    :param output_dir: local dir holding the cached `<base>.summary.md`
        files written by `_process_row()`
    :param dest_dir: destination dir to reconcile into, or None for
        `--dest_type none` (nothing to reconcile)
    :param dry_run: if True, only report what would be copied, without
        touching the filesystem
    :return: merged filenames copied (or, in `dry_run`, that would be
        copied)
    """
    _LOG.debug(hprint.to_str("output_dir dest_dir dry_run"))
    if dest_dir is None:
        return []
    done_rows = [r for r in rows if (r.get("Done") or "").strip() == "yes"]
    copied_filenames = []
    for row in done_rows:
        hn_url = (row.get("Hn_url") or "").strip()
        if not hn_url or not dshdbout.is_hackernews_url(hn_url):
            # Shouldn't happen for a Done=yes row, but guard defensively
            # since item_id extraction below requires a real HN item URL.
            continue
        item_id = dshdbout.extract_item_id(hn_url)
        merged_file = _find_cached_merged_summary(output_dir, item_id)
        if merged_file is None:
            _LOG.warning(
                "Done=yes row for item %s has no cached merged summary "
                "under '%s'; skipping reconciliation for it",
                item_id,
                output_dir,
            )
            continue
        merged_filename = os.path.basename(merged_file)
        dest_file = os.path.join(dest_dir, merged_filename)
        if os.path.exists(dest_file):
            continue
        if dry_run:
            _LOG.info(
                "[DRY_RUN] Would copy '%s' -> '%s'", merged_file, dest_file
            )
        else:
            shutil.copy2(merged_file, dest_file)
            _LOG.info("Copied '%s' -> '%s'", merged_file, dest_file)
        copied_filenames.append(merged_filename)
    return copied_filenames


# #############################################################################
# CLI and Entry Point
# #############################################################################


def _parse() -> argparse.ArgumentParser:
    """
    Parse command-line arguments.
    """
    _LOG.debug(hprint.func_signature_to_str())
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=hparser.CustomHelpFormatter,
    )
    parser.add_argument(
        "-i",
        "--input",
        action="store",
        required=True,
        help="Path to the bookmarks CSV file (must have 'Hn_url' and "
        "'Done' columns); updated in place as rows are processed",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=_DEFAULT_LIMIT,
        help=f"Max number of unprocessed rows to process (default: "
        f"{_DEFAULT_LIMIT})",
    )
    parser.add_argument(
        "-o",
        "--output_dir",
        type=str,
        default=_DEFAULT_OUTPUT_DIR,
        help="Local dir for the raw per-item files from "
        "download_hn_article_to_md.py and the merged summary, cached here "
        f"before being reconciled into --dest_type (default: "
        f"{_DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--dest_type",
        action="store",
        choices=["gdrive", "obsidian", "none"],
        default="gdrive",
        help="Destination merged summaries are reconciled into (default: "
        "gdrive, unchanged default path/behavior): 'gdrive' or 'obsidian' "
        "each map to a built-in default dir (override with --dest_dir); "
        "'none' keeps merged summaries in --output_dir only",
    )
    parser.add_argument(
        "--dest_dir",
        type=str,
        default="",
        help="Override the built-in dir for the selected --dest_type "
        "(ignored for --dest_type none)",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="",
        help="LLM model passed through to download_hn_article_to_md.py "
        "for both summarization phases (article + HN comments); empty "
        "(default) uses that script's own default (currently routed "
        "through OpenRouter; see download_utils.SUMMARY_MODEL)",
    )
    parser.add_argument(
        "--no_incremental",
        action="store_true",
        help="Reprocess rows even if already marked Done, overwriting "
        "existing local per-item output files",
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Dry run mode: show what would be done without actually "
        "executing actions",
    )
    hparser.add_verbosity_arg(parser)
    return parser


def _main(parser: argparse.ArgumentParser) -> None:
    """
    Main entry point.
    """
    _LOG.debug(hprint.func_signature_to_str())
    args = parser.parse_args()
    hdbg.init_logger(verbosity=args.log_level, use_exec_path=True)
    rows = dshdbout.read_csv(args.input)
    hdbg.dassert(rows, "No rows in CSV: %s", args.input)
    columns = list(rows[0].keys())
    hdbg.dassert_in("Hn_url", columns, "CSV must have 'Hn_url' column")
    hdbg.dassert_in("Done", columns, "CSV must have 'Done' column")
    dest_dir = _resolve_dest_dir(args.dest_type, args.dest_dir)
    selected_rows = _select_rows(
        rows, no_incremental=args.no_incremental, limit=args.limit
    )
    if args.dry_run:
        _LOG.warning("DRY RUN MODE: showing what would be done without executing")
    script = hgit.find_file_in_git_tree("download_hn_article_to_md.py")
    if not args.dry_run:
        hio.create_dir(args.output_dir, incremental=True)
        if dest_dir is not None:
            hio.create_dir(dest_dir, incremental=True)
    # Row processing: bounded by --limit, downloads/summarizes/merges new
    # (not-yet-Done) rows.
    num_processed = 0
    num_skipped = 0
    num_would_process = 0
    total_cost_in_dollars = 0.0
    progress_bar = tqdm(selected_rows, desc="Processing bookmarks")
    for row in progress_bar:
        status, row_stats = _process_row(
            row,
            script=script,
            output_dir=args.output_dir,
            model=args.model,
            no_incremental=args.no_incremental,
            dry_run=args.dry_run,
        )
        if status == "processed":
            num_processed += 1
            if row_stats is not None:
                # `row_stats` is the stats.json content; pull out the cost.
                total_cost_in_dollars += row_stats.get(
                    "total_cost_in_dollars", 0.0
                )
                progress_bar.set_postfix_str(
                    f"Cost: ${total_cost_in_dollars:.4f}"
                )
        elif status == "skipped":
            num_skipped += 1
        elif status == "dry_run":
            num_would_process += 1
        if status in ("processed", "skipped") and not args.dry_run:
            # Persist after each row (processed or newly skipped) so an
            # interrupted run can resume without redoing work.
            dshdbout.write_csv(args.input, rows, fieldnames=columns)
    if args.dry_run:
        # `_process_row()` never returns "processed" in dry_run mode (it
        # short-circuits to "dry_run" for otherwise-valid rows), so report
        # what *would* happen using distinct wording.
        _LOG.info(
            "[DRY_RUN] Would process %d/%d selected row(s), would skip %d "
            "(limit=%d)",
            num_would_process,
            len(selected_rows),
            num_skipped,
            args.limit,
        )
    else:
        _LOG.info(
            "Processed %d/%d selected row(s), skipped %d (limit=%d)",
            num_processed,
            len(selected_rows),
            num_skipped,
            args.limit,
        )
    _LOG.info(
        "Total summarization cost for this run: $%.6f", total_cost_in_dollars
    )
    # Destination reconciliation: runs over ALL Done=yes rows every
    # invocation, not bounded by --limit (--limit 0 runs this only).
    copied_filenames = _reconcile_destination(
        rows, output_dir=args.output_dir, dest_dir=dest_dir, dry_run=args.dry_run
    )
    if dest_dir is None:
        _LOG.info("Destination reconciliation skipped (--dest_type none)")
    elif args.dry_run:
        _LOG.info(
            "[DRY_RUN] Would copy/repair %d row(s) into destination '%s'",
            len(copied_filenames),
            dest_dir,
        )
    else:
        _LOG.info(
            "Reconciled %d row(s) into destination '%s'",
            len(copied_filenames),
            dest_dir,
        )


if __name__ == "__main__":
    _main(_parse())
