#!/bin/bash -e

# Make sure $1 contains a skill (e.g., `git.move`)
if [[ -z "$1" ]]; then
    echo "ERROR: Provide a skill name (e.g., git.move)" >&2
    exit 1
fi
SKILL="$1"

# Find the git repository root.
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"

# Check that the corresponding dir doesn't exist (e.g., `.claude/skills/git.move`)
SKILL_DIR="$REPO_ROOT/.claude/skills/$SKILL"
if [[ -d "$SKILL_DIR" ]]; then
    echo "ERROR: Skill dir already exists: $SKILL_DIR" >&2
    exit 1
fi

# Create the dir.
mkdir -p "$SKILL_DIR"

# Create the SKILL.md file inside the dir.
SKILL_MD="$SKILL_DIR/SKILL.md"
cat > "$SKILL_MD" <<EOF
---
name: $SKILL
description:
---
EOF

# Print the full path of the SKILL.md.
echo "$SKILL_MD"
