comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
  show_critical_paths: false

coverage:
  annotations: false
  status:
    project:
      enabled: true
      target_branch: master
      comparator: relative
      threshold: 1
    patch:
      enabled: true
