flag_management:
  individual_flags:
    - name: fast
      carryforward: true
    - name: slow
      carryforward: true
    - name: superslow
      carryforward: true



# Disable per-line comments on pull requests.
comment: false

coverage:
  status:
    project:
      # Post an overall project-level GitHub check summarizing coverage status.
      enabled: true
      # Use the master branch as the baseline for comparison.
      target_branch: master
      # Compare coverage change relative to the baseline branch.
      comparator: relative
      # Fail the status check if coverage drops by 1% or more.
      threshold: 1
      # Specify which flags to include in the project-level coverage calculation.
      flags:
        - fast
        - slow
        - superslow
    patch:
      # Post patch-level coverage checks for pull requests.
      enabled: true
