flag_management:
  default_rules:
    # Do not reuse last coverage if missing.
    carryforward: false
  individual_flags:
    - name: fast
      # Reuse last coverage if missing for true.
      carryforward: true
    - name: slow
      carryforward: true
    - name: superslow
      carryforward: true


# No per-line comments.
comment: false

coverage:
  status:
    project:
      # Post the project‑level GitHub Check.
      enabled: true
      target_branch: master
      # Measure % drop relative to baseline.
      comparator: relative
      # Fail if drop ≥1%.
      threshold: 1
      flags:
        - combined_fast_slow
    patch:
      enabled: false
