flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: fast
      carryforward: true
    - name: slow
      carryforward: true

comment: false
coverage:
  status:
    project: off
    patch: off
