[tool.ruff]
line-length = 80
target-version = "py311"
fix = true
exclude = [
  "**/outcomes/**",
  "**/import_check/example/**"
]

[tool.ruff.lint]
exclude = [
  "**/outcomes/**",
  "**/import_check/example/**"
]

[tool.pyrefly]
# Currently, Pyrefly doesn't officially support [tool.pyrefly] config
# Instead, use CLI flags like `pyrefly lint . --config path/to/config.yaml`
# But you can still define this for documentation or future support
path = "."

[tool.fixit]
lint.ignore_codes = []
lint.enabled = true
lint.format = "text"
lint.exclude = ["tests/fixtures"]
lint.show_source = true
