[tool.ruff]
# Maximum allowed line length for code.
line-length = 81
# Target Python version for linting and autofixes.
target-version = "py311"
# Automatically apply fixes for linting issues when possible.
fix = true
# Exclude specific directories from linting and fixing.
exclude = [
  "**/outcomes/**",
  "**/import_check/example/**"
]
# Format of the output from Ruff.
output-format = "concise"

[tool.ruff.lint]
# Ignore specific lint rules
# E731: Do not assign a `lambda` expression, use a `def`
ignore = ["E731"]

[tool.pyrefly]
# Currently, Pyrefly doesn't officially support [tool.pyrefly] config
# Instead, use CLI flags like `pyrefly lint . --config path/to/config.yaml`
# But you can still define this for documentation or future support
path = "."

[tool.fixit]
lint.ignore_codes = []
lint.enabled = true
lint.format = "text"
lint.exclude = [
  "**/outcomes/**",
  "**/import_check/example/**"
]
lint.show_source = true
