repo_info:
  repo_name: helpers
  github_repo_account: kaizen-ai
  github_host_name: github.com
  invalid_words:

docker_info:
  docker_image_name: helpers

s3_bucket_info:
  unit_test_bucket_name: s3//cryptokaizen-unit-test
  html_bucket_name: s3//cryptokaizen-html
  html_ip: http://172.30.2.44