#!/bin/bash -e

# """
# Recursive `git clean -fd`
# """

source helpers.sh

if [[ -f .gitmodules ]]; then
    echo "===================== supermodule ====================="
fi;
execute "git clean -fd"

if [[ -f .gitmodules ]]; then
  echo "===================== submodule ====================="
  execute "git clean -fd"
fi;
