#!/bin/bash -e

# """
# > git difftool $*
# > gd <dir> <ext>: git difftool on all the files with extension <ext> under
# >   <dir> (e.g., `gd . py`)
# """

source helpers.sh

FILES=$(resolve_diff_files 0 "$@")
execute "git difftool $FILES"
