#!/usr/bin/env python

"""
Merge `origin/master` into the current branch.

# Usage Example

- Merge master into the current branch, aborting if the merge is not a
  fast-forward or the client is not clean, then auto-commit and push:
> git_merge_master.py

- Only preview which files would conflict, without touching the working
  tree, the index, or history:
> git_merge_master.py --dry_run

- Merge without auto-committing/pushing and without fetching submodules:
> git_merge_master.py --no_auto_merge --no_submodules
"""

import argparse
import logging
import re
from typing import List

import helpers.hdbg as hdbg
import helpers.hgit as hgit
import helpers.hparser as hparser
import helpers.hprint as hprint
import helpers.hsystem as hsystem

_LOG = logging.getLogger(__name__)


# #############################################################################
# Fetch
# #############################################################################


def _fetch_master(submodules: bool) -> None:
    """
    Fetch master branch from remote without switching to it.

    Updates the local master branch to track the latest remote master
    without affecting the current branch.

    :param submodules: also fetch master in all submodules (e.g.,
        `helpers_root`). Set to `False` to avoid errors like "refusing
        to fetch into branch ... checked out" when a submodule has its
        master branch checked out in its own git dir (e.g., when the
        submodule is used as a standalone repo)
    """
    # Fetch remote master directly into local master ref (colon syntax).
    cmd = "git fetch origin master:master"
    hsystem.system(cmd, suppress_output=False)
    if submodules:
        # Run the same command on all submodules.
        cmd = "git submodule foreach 'git fetch origin master:master'"
        hsystem.system(cmd, suppress_output=False)


def _add_all_untracked_files(*, exclude_tmp: bool = False) -> None:
    """
    Add all untracked files to Git.

    :param exclude_tmp: skip `tmp.*` files (e.g.,
        `tmp.precommit_output.txt`) generated by the pre-commit hook
    """
    cmd = "git ls-files -o --exclude-standard -z"
    if exclude_tmp:
        cmd += " | grep -zv '^tmp\\.'"
    cmd += " | xargs -0 git add"
    hsystem.system(cmd, suppress_output=False)


# #############################################################################
# Preview
# #############################################################################


def _print_file_list(title: str, files: List[str], *, max_files: int = 50) -> None:
    """
    Print a titled, bulleted list of file paths, truncating if very long.

    :param title: header printed before the list (with the count
        appended)
    :param files: file paths to list
    :param max_files: max number of files to print before eliding the
        rest
    """
    print(f"\n{title} ({len(files)}):")
    if not files:
        print("  (none)")
        return
    for f in files[:max_files]:
        print(f"  - {f}")
    if len(files) > max_files:
        print(f"  ... and {len(files) - max_files} more")


def _preview_git_merge_master(current_branch: str, target_branch: str) -> bool:
    """
    Report, without merging, which files would conflict if `target_branch`
    were merged into `current_branch`.

    This runs an in-memory 3-way merge via `git merge-tree --write-tree`:
    nothing is written to the working tree, the index, or history, and no
    branch is checked out or modified.

    :param current_branch: branch that would receive the merge (e.g.,
        the branch currently checked out)
    :param target_branch: branch to be merged in (e.g., `master`)
    :return: `True` if the merge would be conflict-free, `False` if some
        files would conflict
    """
    # Determine which files each side touched since the merge-base: files
    # touched on only one side always merge trivially, so they don't need a
    # real 3-way content merge.
    _, merge_base = hsystem.system_to_string(
        f"git merge-base {current_branch} {target_branch}"
    )
    merge_base = merge_base.strip()
    _, current_txt = hsystem.system_to_string(
        f"git diff --name-only {merge_base} {current_branch}"
    )
    _, target_txt = hsystem.system_to_string(
        f"git diff --name-only {merge_base} {target_branch}"
    )
    current_files = set(current_txt.splitlines())
    target_files = set(target_txt.splitlines())
    both_sides_files = current_files & target_files
    # Run the in-memory 3-way merge. `git merge-tree` exits with a non-zero
    # code when there are conflicts, so we don't abort on error.
    cmd = f"git merge-tree --write-tree {current_branch} {target_branch}"
    _, txt = hsystem.system_to_string(cmd, abort_on_error=False)
    conflict_files = sorted(
        set(
            re.findall(
                r"^CONFLICT \([^)]*\): Merge conflict in (.*)$",
                txt,
                re.MULTILINE,
            )
        )
    )
    auto_merged_files = set(
        re.findall(r"^Auto-merging (.*)$", txt, re.MULTILINE)
    )
    # Changed on both sides, but the 3-way content merge succeeds.
    clean_merge_files = sorted(auto_merged_files - set(conflict_files))
    # Changed on both sides with no message at all from `git merge-tree`
    # (e.g., both sides made the identical change): also conflict-free.
    other_clean_files = sorted(
        both_sides_files - auto_merged_files - set(conflict_files)
    )
    trivial_files = sorted(
        (current_files | target_files) - both_sides_files
    )
    print(
        "\n" + hprint.frame(f"Preview: merge `{target_branch}` into `{current_branch}`")
    )
    print(
        "(dry run via `git merge-tree`: no files, index, or history touched)"
    )
    _print_file_list("Conflicting files", conflict_files)
    _print_file_list(
        "Files changed on both branches, merge cleanly",
        clean_merge_files + other_clean_files,
    )
    _print_file_list(
        "Files changed on only one branch (always merge trivially)",
        trivial_files,
    )
    is_clean = not conflict_files
    if is_clean:
        print("\nNo conflicts: `invoke git_merge_master` can merge cleanly")
    else:
        print(
            f"\n{len(conflict_files)} file(s) would conflict; resolve "
            "manually or plan for conflict resolution before running "
            "`invoke git_merge_master`"
        )
    return is_clean


# #############################################################################
# Merge
# #############################################################################


def _git_merge_master(
    *,
    abort_if_not_ff: bool = False,
    abort_if_not_clean: bool = True,
    skip_fetch: bool = False,
    auto_merge: bool = True,
    submodules: bool = True,
    dry_run: bool = False,
) -> None:
    """
    Merge `origin/master` into the current branch.

    :param abort_if_not_ff: abort if fast-forward is not possible
    :param abort_if_not_clean: abort if the client is not clean
    :param skip_fetch: skip fetching master
    :param auto_merge: automatically commit and push if merge is
        successful
    :param submodules: also fetch master in submodules (see
        `_fetch_master`)
    :param dry_run: instead of merging, run a dry-run 3-way merge and
        report which files would conflict, which would merge cleanly,
        and which change on only one side. No merge is attempted and
        nothing is written to the working tree, the index, or history
    """
    if dry_run:
        # Fetch so the preview reflects the latest remote master, but never
        # touch the working tree, the index, the current branch, or history.
        if not skip_fetch:
            _fetch_master(submodules)
        current_branch = hgit.get_branch_name()
        _preview_git_merge_master(current_branch, "master")
        return
    # Verify working directory is clean before merging to avoid losing changes.
    hgit.is_client_clean(dir_name=".", abort_if_not_clean=abort_if_not_clean)
    # Fetch latest master from remote to ensure we merge the latest changes.
    if not skip_fetch:
        _fetch_master(submodules)
    # Perform merge, optionally restricting to fast-forward only to maintain linear history.
    cmd = "git merge master"
    if abort_if_not_ff:
        cmd += " --ff-only"
    hsystem.system(cmd, suppress_output=False)
    # Commit and push automatically if merge succeeded and user requested it.
    if auto_merge:
        # Add any remaining untracked files, skipping tmp files generated by
        # this script itself (e.g., `tmp.precommit_output.txt` from the
        # pre-commit hook).
        _add_all_untracked_files(exclude_tmp=True)
        _LOG.info("Auto-merge enabled: committing and pushing changes")
        cmd = 'git commit -am "Merge master" && git push'
        hsystem.system(cmd, suppress_output=False)


# #############################################################################
# CLI
# #############################################################################


def _parse() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=hparser.CustomHelpFormatter,
    )
    parser.add_argument(
        "--abort_if_not_ff",
        action="store_true",
        help="Abort if fast-forward is not possible",
    )
    parser.add_argument(
        "--no_abort_if_not_clean",
        action="store_true",
        help="Do not abort if the Git client is not clean",
    )
    parser.add_argument(
        "--skip_fetch",
        action="store_true",
        help="Skip fetching master",
    )
    parser.add_argument(
        "--no_auto_merge",
        action="store_true",
        help="Do not automatically commit and push after a successful merge",
    )
    parser.add_argument(
        "--no_submodules",
        action="store_true",
        help="Do not also fetch master in submodules",
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Instead of merging, report which files would conflict without "
        "touching the working tree, the index, or history",
    )
    hparser.add_verbosity_arg(parser)
    return parser


def _main(parser: argparse.ArgumentParser) -> None:
    args = parser.parse_args()
    hdbg.init_logger(verbosity=args.log_level, use_exec_path=True)
    _git_merge_master(
        abort_if_not_ff=args.abort_if_not_ff,
        abort_if_not_clean=not args.no_abort_if_not_clean,
        skip_fetch=args.skip_fetch,
        auto_merge=not args.no_auto_merge,
        submodules=not args.no_submodules,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    _main(_parse())
