#!/bin/bash -e

# """
# Print the status of the clients and of the submodules with
# > git status --short
# """

source helpers.sh

if [[ -f .gitmodules ]]; then
    echo "===================== supermodule ====================="
fi;

execute_with_verbose "git branch --show-current"
execute_with_verbose "git status --short $*"

if [[ -f .gitmodules ]]; then
  echo "===================== submodule ====================="
  execute_with_verbose "git submodule foreach git branch --show-current"
  execute_with_verbose "git submodule foreach git status --short $*"
fi;
