#!/bin/bash -e

# """
# Print the status of the clients and of the submodules with
# git status
# """

source helpers.sh

if [[ -f .gitmodules ]]; then
  echo "===================== supermodule ====================="
fi;

execute "git branch --show-current"
execute "git status $*"

if [[ -f .gitmodules ]]; then
  echo
  echo "===================== submodule ====================="
  execute "git submodule foreach git branch --show-current"
  execute "git submodule foreach git status $*"
fi;
