#!/usr/bin/env python

"""
rig - Utility for ripgrep searches and directory operations.

# Search for "TODO" in Python files in src directory
> rig "TODO" src py

# Search for "TODO" in all files in src directory
> rig "TODO" src

# Search for "TODO" in all files in current directory
> rig "TODO"

# Search in Python files in current directory
> rig "import" py

# Search in JavaScript files with case-insensitive matching
> rig "import" . js -i
"""

import dev_scripts_helpers.system_tools.lib_rig as lib_rig

if __name__ == "__main__":
    parser = lib_rig.parse()
    exit(lib_rig.main(parser))
