authors:
  gpsaggese:
    name: GP Saggese
    description: Chief Technology Officer
    avatar: https://avatars.githubusercontent.com/u/33238329
    url: https://github.com/gpsaggese
  jsherlock:
    name: Joel Sherlock
    description: Chief Executive Officer
    avatar: https://avatars.githubusercontent.com/u
    url: 
  psmith:
    name: Paul Smith
    description: Chief Scientist
    avatar: https://avatars.githubusercontent.com/u/7649219?v=4
    url: https://github.com/gitpaulsmith
