name: Test Reusable Fast tests
on:
  # Run on every PR to master that is ready to review (i.e., not draft).
  pull_request:
    # https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/19
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master    
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run_fast_tests:
    uses: ./.github/workflows/tests.yml
    with:
      test-name: run_fast_tests
    secrets: inherit
