name: Test Reusable Fast tests
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run_fast_tests:
    uses: ./.github/workflows/tests.yml
    with:
      test-name: run_fast_tests
    secrets: inherit
